theme: jekyll-theme-cayman
title: Métodos Numéricos con Python - Parte 2 Álgebra Lineal Numérica
description: Aprende todos los algoritmos para trabajar con matrices y sistemas para aplicarlos a IA y ML y prográmalo en Python
url: https://www.udemy.com/course/draft/3882744/?couponCode=B1C0DA66D85CB35C9925
link: https://www.udemy.com/course/draft/3882744/?couponCode=B1C0DA66D85CB35C9925
